name: Bug Report
description: File a bug report
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what you see!
      value: "It did a thing!"
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: What did you expect to happen?
      description: A description of how you would think the Trance Stack should have worked
      placeholder: I expected it to...
      value: "I expected it to"
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: What version of Remix are you using?
    validations:
      required: true
