name: Playwright Tests
on:
  pull_request:
    branches: [ main ]
jobs:
  test:
    name: "Playwright Tests"
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up node
      uses: meza/action-setup-node-npm@main
      with:
        command: install
        node-version: latest
        cache-name: 'playwright'
    - name: Create envfile
      uses: SpicyPizza/create-envfile@v1.3
      with:
        envkey_AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
        envkey_AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
        envkey_AUTH0_CLIENT_SECRET: ${{ secrets.AUTH0_CLIENT_SECRET }}
        envkey_SPLIT_SERVER_TOKEN: ${{ secrets.SPLIT_SERVER_TOKEN }}
        envkey_SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
        envkey_NODE_ENV: ${{ vars.NODE_ENV }}
        envkey_HOTJAR_ID: ${{ vars.HOTJAR_ID }}
        envkey_MIXPANEL_API: ${{ vars.MIXPANEL_API }}
        envkey_MIXPANEL_TOKEN: ${{ vars.MIXPANEL_TOKEN }}
        envkey_COOKIEYES_TOKEN: ${{ vars.COOKIEYES_TOKEN }}
        envkey_SENTRY_DSN: ${{ vars.SENTRY_DSN }}
    - name: Build
      run: npm run build
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: DEBUG=pw:webserver npm run int
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
